### ISSUE TITLE
Set properties as expression instead of attribute

### ISSUE THREAD

**Issue by Maismaus** [hunter-koppen/mapsPolygon#2]
Setting polygon properties such as Opacity as expression instead of attribute gives much more flexibility. In my case, I have a large number of entities in the polygon so I need to limit my request body as much as possible. I don't want to put Opacity in every polygon object because it is the same for every object anyway. 
If it's an expression you can choose $currentObject/Opacity or $parentObject/Opacity or a hardcoded value.

**Comment by hunter-koppen** [comment]
Great idea, I'll try and find some time soon to update the widget

**Comment by hunter-koppen** [comment]
@Maismaus Finally found some time to update the widget, I've updated all attributes to expressions except for the polygon coordinates itself
